;
; LocalStateQuery mini-protocol.
;

localStateQueryMessage
  = msgAcquire
  / msgAcquired
  / msgFailure
  / msgQuery
  / msgResult
  / msgRelease
  / msgReAcquire
  / lsqMsgDone

acquireFailurePointTooOld     = 0
acquireFailurePointNotOnChain = 1
acquireFailureStateIsBusy     = 2

failure      = acquireFailurePointTooOld
             / acquireFailurePointNotOnChain
             / acquireFailureStateIsBusy

leashId      = word32

query        = any
result       = any

msgAcquire   = [0, point, ? leashId]
             / [8, ? leashId]
             / [10, ? leashId]
msgAcquired  = [1]
msgFailure   = [2, failure]
msgQuery     = [3, query]
msgResult    = [4, result]
msgRelease   = [5, ? bool]
msgReAcquire = [6, base.point]
             / [9]
             / [11]
lsqMsgDone   = [7, ? leashId]

;# import network.base as base
